version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python:
    build: # La imagen que descargamos la vamos a usar para hacer una propia con el build
      context: ./python # y le vamos a pasar el Dockerfile que esta dentro del dir ./filebeat